version: "3.2"
services:
  firestore:
    # Check why the firestore image is not able to dynamic env replacement
    # So temporary we can run on :8080
    # This docker-compose we will only use only locally, because GCP do not use it
    # GCP will deploy only "server" image nothing more
    image: mtlynch/firestore-emulator-docker
    environment:
      - FIRESTORE_PROJECT_ID=dummy-project-id
      - PORT=8080
    ports:
      - "8080:8080"

  server:
    build: '.'
    environment:
      - PORT=3000
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - GCLOUD_PROJECT=local-project-id
    ports:
      - "3000:3000"
    depends_on:
      - firestore
