name: Quality check

on:
  push:
    branches-ignore:
      - master

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Run DB locally
        run: npm run db

      - name: Dependency instalation
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Tests
        run: npm run test
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080
          GCLOUD_PROJECT: local-project-id

      # We modify the PORT env to be sure that we still allow to modify our docker container's port
      - name: Building and run docker container
        run: |
          docker build . -t zombie-image
          docker run -d -p 4000:3000 --env "PORT=3000" zombie-image
          sleep 5

      - name: Check if service is up
        run: curl "http://localhost:4000" &>/dev/null && echo OK || exit 1
